$schema: "http://json-schema.org/draft-07/schema#"
name: mint-local
version: "v1"

defaultModel: Qwen Coder (Cloud)
tabAutocompleteModel: Qwen Coder (Cloud)

models:
  - title: Qwen Coder (Cloud)
    provider: ollama
    apiBase: https://ollama.com
    model: qwen3-coder:480b
    apiKey: ${OLLAMA_API_KEY}
